services:
  - type: web
    name: barbera-frontend
    env: static
    rootDirectory: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
